steps:
  - name: 'hashicorp/terraform:1.0.0'
    args:
      - '-c'
      - >
        cd $_MODULE_TO_RUN

        terraform init
        -backend-config "bucket=$_BUCKET"
        -backend-config "prefix=$_PREFIX"

        terraform apply
        -var "project_id=$_PROJECT"
        -var "region=$_REGION"
        -var "domain_prefix=$_DOMAIN_PREFIX"
        -var "ons_ips=$_ONS_IPS"
        -var "developer_ips=$_DEVELOPER_IPS"
        -var "dns_project_id=$_DNS_PROJECT_ID"
        -var "managed_zone_name=$_MANAGED_ZONE_NAME"
        -var "application_image_repository=$_APPLICATION_IMAGE_REPOSITORY"
        -auto-approve
    id: tf apply
    entrypoint: sh
timeout: 1200s
